

#https://drive.google.com/file/d/1CnbWap-Q34omy-_Nke-N6wqCq50pXu0T/view?usp=drive_link -- Video timestamp to.
label inscription_in_stone:#100% complete Needs test...
    scene image "07_inscription_in_stone/01_quote.png"
    "— The Dark Fools lament"

    scene image "07_inscription_in_stone/02_establishing_shot.png" # TODO Maybe remove the "inscriptions in stone"? Or get the game concept art of this area...
    mama "This is the final stop on your journey."
    mama "The time has come to restore the final memory."
    mama "We will regain all that you have lost..."
    mama "So that we might fulfill your wish."
    "The two start pressing forward to next scarecrow."
    scene image "07_inscription_in_stone/02_1_Scarecrow_shot.png"
    mama "Your memories are engraved in this scarecrow. Let us begin..."
    
    # Story 1
    # 1:57
    # A title screen or chapter introduction for a game or visual novel, displaying "Redemption: Black" and "Monstrous World" within an ornate, aged-looking border with a sepia-toned background.
    scene image "07_inscription_in_stone/03_BG_redemption_1.png"
    "Story 1: Monstrous World"
    scene image "07_inscription_in_stone/04_BG_Establishing_Shot_1.png" # 2:13
    "Surrounded by machines, the monster stirs… awakening to a world unknown."
    "Gear screetching and clanging..."
    "Finding itself in a new form..."
    "A monster...\n Thats mechanical in nature."
    "With unsteady steps, the monster limps forward—making slow, desperate progress."
    scene image "07_inscription_in_stone/05_bg_Meeting_mama.png"
    mama "Welcome. It took you a little while to get here, didnt it?"
    mama "This is the last memory; the last tale."
    mama "Lets move on, shall we?"
    mama "This memory differs from all the rest." # 2:52
    mama "The world within is terribly unstable."
    mama "Stay close to mama so you dont get lost, all right?"
    scene image "07_inscription_in_stone/06_bg_moving_on.png"# 2:59
    "The two begin to make haste."
    scene image "07_inscription_in_stone/07_bg_monster_interaction_1.png"
    "Until they stumble upon a lone monster—one that is closly akin to the monster." # 3:20

    "Its eyes are wondering mumbling to itself."
    spaceyMonster "Ahhh... More... I need more..."
    "Mama continues on, Ignoring the disturbance."
    scene image "07_inscription_in_stone/08_bg_moving_on.png"
    mama "Monsters like you live in this world."
    mama "That should be obvious, though."
    mama "Its quite unlike the human world, dont you think?"
    scene image "07_inscription_in_stone/09_bg_monster_interaction_2.png" # 3:57
    mama "Oh! Look at that over there."
    mama "Those are monsters—creatures of the same type as you."
    mama "They certainly seem to be having fun! I wonder what they're talking about?"
    flippantMonster "What? Nuh-uh, this dreams mine!"
    flippantMonster "You want it? Come get it!"
    sullenMonster "Another new dream..."
    sullenMonster "If I just keep going, then one day..."
    shadyMonster "Uuurgh... Youuu!"
    mama "Look out! That one is—"
    "A struggle ensues as the two monsters clash, each blow forcing the aggressor back from his path."
    "The monster limps onward, the fallen aggressor lying still behind him."
    scene image "07_inscription_in_stone/10_bg_post_encounter_2.png"
    mama "The dark foes will attack you here as well, Im afraid. Do be careful."
    mama "As you dream eaters devour said dreams, you will change."
    mama "Eventually, you will take on a human form."
    mama ......
    mama "Eventually, you will take on a human form."


    #Story exit 5:52 May remove this mama section...
    scene image "07_inscription_in_stone/11_bg_scarecrow_exit.png"
    mama "I know its painful, but lets keep going."
    mama "These memories are deeply entangled with you; restoring them will not be easy."
    mama "Do you know what that monster is?"
    mama "It is a creature who steals and eats human dreams for want of their form."
    mama "But perhaps you know more about that than I do."
    fio "....." # Added this in -3rd
    mama "Come, then. Let us search for the next scarecrow and memory."
    "The girl and the creature continue onward across the cold, lifeless stone floor. To the next scarecrow."
    #mama "Do you remember how to use this terminal?"
    #mama "You came through here with her once, didnt you?"
    #mama "This is the second memory. Are you ready?"
    #9:19
    #Story 2 8:26
    scene image "07_inscription_in_stone/12_bg_redemption_2.png"
    "Story 2: Violent Greed"
    scene image "07_inscription_in_stone/13_bg_establishing_shot_part1.png"
    "With a sudden lurch, the gears spin backward—bathing the room in an eerie green radiance."
    scene image "07_inscription_in_stone/14_bg_establishing_shot_part2.png"
    mama "Be ready."
    mama "The pain you feel right now?"
    mama "It will only grow deeper as we restore this memory."
    scene imaage "07_inscription_in_stone/15_bg_progression_shot.png"
    mama "We are moving ever closer to the deepest parts of this memory."
    mama "And as we do, you grow nearer to your original self."
    mama "Be careful that you dont get swallowed up."
    mama "Old selves have a way of doing that..."
    scene image "07_inscription_in_stone/16_bg_deadly_encounter.png"
    "At last, they step into an open expanse—its emptiness heavy and unsettling."
    "Where monsters of the same kind lie torn apart, impaled, and broken."
    mama "Oh dear. Do stay alert, now."
    mama "I recognize this method of killing."
    mama "It means they have intruded nearby."
    scene image "07_inscription_in_stone/17_bg_the_monster.png"
    "Proceeding into slaughter, a sight awaits—a creature hunched over, devouring another's dreams."
    franticMonster "Dreams... DREAMS!"
    franticMonster "I NEED MORE DREEEEEEEAMS!"
    mama: "This one is going to destroy your memory."
    mama: "Your wish wont come true if you dont restore this, you know?"
    franticMonster "Its not enough... I cant..."
    franticMonster "I cant become human like this!"
    scene image "07_inscription_in_stone/18_bg_monster_rage.png"
    "Suddenly, The monster takes a step and lets out a mighty roar!"
    mama "Its coming! Look out!" # 10:11
    scene image "07_inscription_in_stone/19_bg_monster_fighter_1.png"
    "The two monster clash! Holder eachother at bay."
    "Then they push themselves free of each other..."
    scene image "07_inscription_in_stone/20_bg_monster_fight_2.png"
    "The monster braces, preparing to unleash a second strike..."
    scene image "07_inscription_in_stone/21_bg_monster_fight_3.png"
    "With unyielding resolve, the monster cleaves through the fanatic beast, felling it in a single motion."
    franticMonster: "Noooo... I was...so close..." # 10:23
    mama "There are two contradictory beings within your memory:"
    mama "One is a monster that wishes to become human."
    mama "The other is a monster that rejects this thought."
    mama "You, I am afraid, were stuck in the middle."
    mama "......"
    mama "What do you truly wish to do?"
    scene image "07_inscription_in_stone/22_bg_zoom_out_ending.png"
    "....."
    # Story 2 end 11:00

    # Mama / Levania(fio) and Cage
    #mama: "Are you all right? Can you walk?"
    #mama: "Like I said before, the more we restore, the deeper your pain will grow."
    #mama: "The dark foes attacks grow ever more vehement."
    #mama: "...The path has been cut off."
    #mama: "Though if the path was there, even if is no going back."
    #mama: "When we finish restoring all of these memories, I will ask you one more time."
    #mama: "So prepare yourself for that moment, all right?"
    
    # Story 3 14:14
    scene image "07_inscription_in_stone/23_redemption_3.png"
    "Story 3: Diseased Impulse"
    scene image "07_inscription_in_stone/24_establishing_shot.png"
    "The gears grind to a halt before jolting violently into reverse."
    "Turning the grim green sky into a stone cold white."
    scene image "07_inscription_in_stone/25_establishing_shot_2.png"
    mama "Let us proceed."
    "Both the creature and monster proceed to walk on..." # TODO may remove let's see...
    mama "Our only path is straight ahead, after all."
    mama "It is difficult for any creature to fight their instincts."
    mama "The wish to become human... The urge to eat dreams..."
    mama "Those are the greatest desires for monsters such as you."
    mama "They are your very reasons for living."
    mama "Denying them would be the same as denying yourself."
    scene image "07_inscription_in_stone/26_bg_obstruction_1.png"
    "The monster and creature happen upon a ravine, barring their path."
    "With a single strike, the monster fells a tree, laying it across the ravine to bridge their way forward."
    scene image "07_inscription_in_stone/27_bg_obstruction_2.png"
    "....."
    scene image "07_inscription_in_stone/28_bg_obstruction_3.png"
    "Both move on across the unstable bridge watching their step."
    scene image "07_inscription_in_stone/29_bg_encounter_1.png"
    "They wonder apon a creature guarding earie cave surounded by black birds."
    scene image "07_inscription_in_stone/30_encounter_2.png"
    "Number of small birds flock in one by one."
    #16:18
    blackBird "WHY"
    blackBird "THAT CHILD"
    scene image "07_inscription_in_stone/30_encounter_3.png"
    blackBird "BE HUMAN"
    blackBird "DOESNT MATTER"
    scene image "07_inscription_in_stone/32_encounter_4.png"
    blackBird "TAKE"
    blackBird "WHO CARES"
    "The birds twitch and rufferling their feathers repeating, repeating, again and again..."
    "Suddenly the Guard beings questioning you..."
    guardianMonster "You wanted to be human, yeah?"
    guardianMonster "That kid was just food."
    guardianMonster "Why are you letting it bother you now?"
    mama "Dont let them confuse you."
    mama "They will intrude on your hesitation."
    "The monster strucks down the illusion that bars its way. The flock scattering away!"
    mama "Once they read your thoughts, they say them out loud."
    mama "Then they creep into your memory while youre shaken and attempt to destroy it."
    mama "Be careful, okay?"
    "The duo proceed through the swirling cave..."
    scene image "07_inscription_in_stone/33_bg_section_2.png"
    "Stepping out of the darkness, you find yourself in a land of mirrors—endless reflections stretching in every direction."
    mama "Remember back then?"
    mama "You met a human."
    mama "You devoured all of her dreams whole."
    mama "Then you took her body and became human."
    scene image "07_inscription_in_stone/34_bg_transformation_1.png"
    "Wasting no time, you hurry forward… when suddenly, the clockwork spins into motion, and the sky shifts to a bright sunlight, painted in beautiful yellows."
    mama "The restoration is almost complete. Brace yourself."
    # Story 3 END 18:32
    
    #As this one give details to the story i'll keep it.
    scene image "07_inscription_in_stone/35_bg_mama.png"
    "After emerging from the third scarecrow, the two press on toward the next."
    "The girl limps across, mirroring the monster, struggling to keep her balance."
    mama "Can you still walk?"
    mama "...All right."
    mama "Regardless of what you choose, the next memory will be the last."
    mama "...Lets get a move on."
    mama "Restoring the tale of what you have done is penance for your sins."
    mama "But soon that, too, will come to an end."
    mama "Will you realize your wish? Or..."
    mama "This is the last—truly and well the last memory."
    mama "The moment you complete this restoration, you will regain all you have lost."
    mama "And there, you will find your sins waiting."
    

    # Story 4 22:58
    scene image "07_inscription_in_stone/36_redemption_4.png"
    "Story 4: Dark Violation"
    scene image "07_inscription_in_stone/37_bg_establishing_shot.png"
    mama: "The mirror reflects your self."
    mama: "Come now, lets keep going."
    mama: "You need to face your sins."
    scene image "07_inscription_in_stone/38_bg_reflection_of_one_self.png"
    "The monster confronts a large mirror, and within it, a little girl appears—chains wrapped around her wrists and neck."
    "Whom stands staring back."
    mama "That girl is the one from whom you stole dreams."
    mama "You devoured her dreams."
    mama "You stole her body. You became human."
    mama: "And that is the form you take now: the sinful girl in black."
    mama: "Yes, something came from all this:"
    mama: "you fulfilled your desires as a monster."
    mama: "But the poor girl, with all her dreams taken away..."
    mama: "......"
    mama: "Well, you simply couldnt live with that."
    mama "Because you..."
    mama: "Because you and the girl..."
    mama: "You were going to be friends."
    mama: "And yet..."
    mama: "Her dreams were taken from her."
    mama: "So she took on the form of the monster in your place..."
    mama "and still wanders The Cage even now."
    scene image "07_inscription_in_stone/39_bg_mirror_transform.png"
    "Suddenly the monster and the girl get engulfed in darkness and light..."
    scene image "07_inscription_in_stone/40_bg_their_new_form.png"
    "Swapping their places."
    mama: "The time has come."
    scene image "07_inscription_in_stone/41_bg_final.png"
    mama: "You have righted all the memories you were meant to fix."
    mama: "Now you will take back your final fragment."
    mama: "And with that, you will answer my question again."
    scene image "blackscreen.jpg"
    jump withered_crimson
    
