


#The First night withered crimson.
label withered_crimson # 100% complete with images needs testing...

    scene image "08_withered_crimson/01_next_day.png"
    ""
    scene image "08_withered_crimson/02_establishing_shot.png"##TODO change this up in the future.
    "Withered Crimson"
    scene image "08_withered_crimson/03_introductions_1.png"
    "A creature and a monster stand together, waiting…"
    "Dressed as though he were a mailman, the creature wears a small hat and carries a bag at his side."
    "The monster waits in silence, hunched over, its impatience clear."
    #00:19
    carrier "I believe it is now night in that world."
    carrier "The slumbering young miss will soon arrive."
    scene image "08_withered_crimson/03_introductions_2.png"
    carrier "Right then. Here we go!"
    carrier "Welcome to The Cage, young miss! It is the world connected to your dreams."
    fio "This place is called... The Cage?"
    carrier "Indeed it is."
    fio "Wooow... Oh, Mr. Monster! You're back."
    fio "You're gonna eat my dreams like you promised, right?"
    levania "...Hmph."
    carrier "Now then, if you would both please proceed forward."
    scene image "08_withered_crimson/04_on_the_move.png"
    "Together, the three press deeper into the cage, the lush red leaves tittering beneath each step."
    carrier "To think we would so quickly find a client whose interests match our own."
    carrier "A fine outcome for all concerned, says I!"
    carrier "I shall explain all you need to know as we make our way."
    carrier "Soonest begun, soonest done, eh? Ha ha! Let us be off!"
    fio "This is way nicer than the place where I was locked up."
    #carrier "Ah, yes. An elevator. We truly do have all the modern amenities here!"
    #levania "You talk too much."
    scene image "08_withered_crimson/05_first_scarecrow_1.png"
    fio "What's that?"
    carrier "A Dark Scarecrow—though I am uncertain who first gave them that moniker."
    fio "So this scarecrow is my scary dream?"
    carrier "Er, not exactly—although they are similar in a number of respects."
    fio "Take care of my dreams, Mr. Monster!"
    levania "I will—but only because I want to."
    #Story 1 start
    scene image "08_withered_crimson/06_story_1.png"
    "Story 1: 466c6f77657273" # 466c6f77657273 = Flowers TODO decide to put the hex to txt or leave it as hex.
    scene image "08_withered_crimson/07_story_establishing_shot.png"
    "A shopping mall. A common sight."
    "A family. A common sight."
    "Though seemingly mundane, these are truly the most blessed and rare of days."
    "Thankful for the gift of routine, the couple enjoys their ordinary lives."
    scene image "08_withered_crimson/08_shopping.png"
    wife "Go on, Son. Pick out your birthday gift."
    son "No, something cooler."
    son "Yeah! THIS one!"
    "Checkout Bot: Transaction complete. Have a nice day."
    son "Thanks, Mom! Thanks, Dad!"
    wife "H-hey, no running! Heh. He'll never learn."
    scene image "08_withered_crimson/09_encounter_1.png"
    "The ground begins to tremble as screams erupt from outside the shopping mall."
    resident "AAAAAH!"
    resident "Wh-what's that!"
    wife "Son! Where are you?"
    scene image "08_withered_crimson/10_enounter_2.png"
    "There, poised to attack"
    "There, poised to attack their child, is what appears to be a massive flower."
    "The farther fends the aggresive flowers, They make flight into the distance."
    scene image "08_withered_crimson/11_post_encounter_1.png"
    wife "No... Wake up! WAAAKE UUUP!"
    wife "Somebody call an ambulance!"
    scene image "08_withered_crimson/12_nightmare.png"
    "A nightmare—one that repeats time and again and leads back to a reality of despair."
    wife "...That time is gone."
    "His wife's eyes are dim pools filled with resignation, misery, and loss."
    "But they have sworn to enact revenge on the Flowers."
    "It is the only thing that keeps him moving forward."
    #Story 1 end


    #carrier "In order to eat the girl's dreams, we must first restore these memories which happen to be her dreams' original forms."
    #carrier "Anytime we find one of these Dark Scarecrows, we should proceed with its restoration posthaste!"
    #fio "What was my dream about?"
    #carrier "I fear it was a horrid tale of flower monsters that kill people."
    #carrier "Fret not! When you wake, you will remember nothing of these terrible visions."
    #carrier "Goodness, what is this?"
    #carrier "The dark foes have encroached on The Cage!"
    #carrier "We cannot permit them to affect the dreams, so let us square them away."
    #fio "My dreams are always so scary."
    #fio "I don't know the people in them, but they all get hurt or die."
    #carrier "Mmm, yes. You appear to be a human particularly suited for this world."
    #carrier "Perhaps these memories from across space and time play out as dreams to you."
    #fio "I didn't understand most of that, but, um... Okay."
    #fio "Have a nice time, Mr. Monster!"
    

    #Story 2 Start 9:20
    scene image "08_withered_crimson/13_story_2.png"
    "Story 2: 4f72646572" # Order
    scene image "08_withered_crimson/14_establishing_shot.png"
    "P.A: Registration codes F311 through J821."
    "P.A: Report to the feeding hall on the eighth floor for nourishment."
    "The announcement comes at the same time every day."
    "It notifies those in white of mealtimes."
    "As ever, the man dutifully makes for the feeding hall."
    "The white marks him—and all others who wear it—as people without freedom."
    "The rules must be obeyed."
    scene image "08_withered_crimson/15_order.png"
    "Like caddle they march through the scanner one by one."
    scene image "08_withered_crimson/16_malfunction.png"
    officer "H801, you're showing errors."
    officer "Come here."
    scene image "08_withered_crimson/17_malfunction_1.png"
    h801 "No... NO!"
    "As the woman tries to escape, the hue in her eyes changes from unease to madness."
    h801 "NooOOOoOOOooo... MmmYyy...miiNNd..."
    scene image "08_withered_crimson/18_malfunction_2.png"
    officer "H801, proceed to the maintenance room."
    h801 "...Understood."
    "The actions and thoughts of the prisoners in white are not theirs to control."
    officer "You have no freedom. Remember this always."
    officer "Now ready yourselves for the next battle."
    scene image "08_withered_crimson/19_foodhall.png"
    "Both move forward into the food hall."
    "P.A: Alert. Alert."
    "P.A: Flowers have been sighted in Area AL-18."
    "P.A: Prisoner codes A-H:Go to the transport room."
    "P.A: Alert. Alert."
    "An alarm echoes through the facility announcing the arrival of the Flowers."
    "The same unearthly beings that killed their son and tore their once-happy family apart."
    "They are the gravest threat the world has ever known."
    #Story 2 ends 12:23
    image scene "08_withered_crimson/20_joiner.png"
    carrier "It appears the memories saved in these scarecrows are from a world whose people do not know freedom."
    carrier "How terribly suffocating."
    fio "A world without freedom?"
    fio "So the world has a collar like I do?"
    carrier "Well, it does not actually have a collar..."
    carrier "If I may ask, young miss, why DO you wear that collar?"
    fio "I wear a collar 'cause the law says I have to."
    carrier "...Yes, well, I suppose you have your reasons."
    fio "I wish I could have happy dreams."
    fio "Maybe one about cute clothes or pretty jewelry?"
    fio "Or a cake that never runs out! ...Or my mommy's stew."
    levania "Dream whatever dream you like, so long as I get to eat it."
    carrier "Ah, look! Scarecrow number three at last!"

    #carrier "Oh ho! A dead end! Hmmmm, whatever shall we do?"
    #levania "Why are you so smug?"
    #carrier "Ha ha! It was actually a warp point! Clever, no?"
    #fio "Whoa! That was crazy!"
    #carrier "What a convenient world we live in, wouldn't you say?"
    #carrier "Ah, look! Scarecrow number three at last!"
    
    #Story 3
    scene image "08_withered_crimson/21_story_3.png" 
    "Story 3: 41737361756c74" #Assault
    scene image "08_withered_crimson/22_transport_1.png"
    "The prisoners are transported in cramped, stuffy containers as if they were mere cargo."
    "The Flower threat has forced the government to conscript civilians as soldiers."
    "The man and his wife are no exception to this rule."
    scene image "08_withered_crimson/23_to_battle.png"
    officer "Objective sighted ahead. Multiple targets confirmed."
    "The prisoners charge the massive Flowers, intent on eliminating them."
    "Another day. Another battle. A common sight."
    scene image "08_withered_crimson/24_the_battle.png"
    "But this time, they discover a larger, more sinister Flower than any they have yet seen."
    wife "This isn't good. We have to go, now!"
    scene image "08_withered_crimson/25_allies.png"
    "Just when all hope seems lost, their allies come to the rescue."
    "They cannot even thank them by name, for they are known only by letters and numbers."
    "But somehow, they have a greater sense of solidarity than when they had been free."
    "...Or so they had thought."
    wife "Thank you, everyone."
    scene image "08_withered_crimson/26_machines.png"
    wife "Huh...?"
    #Story 3 END
    
    #carrier "Well done! Though I do wonder what happened to those prisoners..."
    #fio "Did someone get hurt again?"
    #carrier "Don't trouble yourself too much about it, young miss."
    #carrier "Our memory restoration is proceeding rather smoothly, don't you think?"
    #levania "I'm tired. This place is far too big."
    #carrier "The next restoration will be tonight's last, so let us pick up the pace!"
    #fio "Kay."
    #carrier "I must say, I've never met a human who saw weapon memories as dreams."
    #fio "So I'm weird?"
    #carrier "I must say, I've never met a human who saw weapon memories as dreams."
    #carrier "Of course not! You are a most valuable samp— Er, client! Yes, that's it."
    #fio "What does eating dreams feel like, Mr. Monster?"
    #fio "Are they yummy?"
    #fio "I'm sorry if they're not."
    #levania "Taste is meaningless."
    #carrier "Oh ho, we are in the home stretch now. Let's go!"
    #fio "Good luck, Mr. Monster!"
    
    #Story 4
    scene image "08_withered_crimson/27_story_4.png"
    "Story 4: 4f75747369646572" # Outsider
    scene image "08_withered_crimson/28_establishing_shot.png"
    "Their fellow prisoners remain frozen in place like a people somehow out of time."
    "The man and his wife look on, trying desperately to make sense of what is happening."
    scene image "08_withered_crimson/29_marching.png"
    "Suddenly the prisoners begin to march, their footsteps all in perfect synch."

    scene image "08_withered_crimson/30_the_ledge.png"
    "The man and his wife behold a sight most uncanny."
    wife "What are they doing?"
    scene image "08_withered_crimson/31_falling.png"
    "Without a word, the prisoners begin to throw themselves into the depths below."
    officer "Hmm? What is this?"
    officer "Why are you two not following orders?"
    scene image "08_withered_crimson/32_attack.png"
    officer "Tsk. More errors. Dispose of them!"
    scene image "08_withered_crimson/33_no_match.png"
    "The man and his wife prove no match for their fellows."
    officer "Would you like to hear a secret before you die?"
    "The officer begins to tell them about the strategy they use to fight the Flowers."
    "Though strategy is a kind word for it."
    "'Experiment' is far more appropriate."
    "Data from the prisoners' battles with the Flowers is recorded and analyzed."
    "Any found wanting—or any who exhibit a sense of self—are determined to be 'defective.'"
    "...And are disposed of by the organization."
    scene image "08_withered_crimson/34_sword_1.png"
    "The officer raises his sword!"
    scene image "08_withered_crimson/35_sword_2.png"
    "....."
    scene image "08_withered_crimson/36_sword_3.png"
    "....."
    scene image "08_withered_crimson/37_sword_4.png"
    wife "Run...my love..."
    scene image "08_withered_crimson/38_post_fall.png"
    "When the man awakens, he sees his fellow prisoners."
    "He is the only survivor."
    "This is unforgiveable. Unforgiveable. Unforgiveable."
    scene image "08_withered_crimson/39_his_pain.png"
    "In the depths of the earth, the man emits a roar of pain."
    # Story 4 END 24:30
    scene image "game/images/08_withered_crimson/40_back_cage.png"
    carrier "To think he lost not only his child, but his wife as well..."
    carrier "Such sadness could scarcely be described with words."

    carrier "At any rate, this concludes tonight's memory restoration."
    carrier "And now, the moment you've been waiting for: dream time!"
    carrier "Eat the nightmares before our young miss here wakes up."
    carrier "You will need to consume many more dreams if you wish to become human, you know."
    carrier "Oh, my. It's almost time for our young miss here to wake up."
    fio "I had lots of fun today. See you tomorrow, Mr. Monster!"
    carrier "Let us be on our way as well."
    "They depart from the little girl allowing her to awake."
    jump piles_of_leaves
