
#The Second Night: Piles of Leaves
label piles_of_leaves:
    scene image "09_piles_of_leaves/01_opening.png"
    "D:\Users\F66x-RV12.02\unknown"
    
    scene image "09_piles_of_leaves/02_establishing_shot.png"
    carrier "And... Ah, yes. There we are."

    scene image "09_piles_of_leaves/03_girl_and_monster.png"
    fio "Hello, Mr. Monster."
    fio "I didn't have ANY dreams last night!"
    carrier "Such is the power of a dream eater. He dined quite well, oh yes!"
    fio "I'm excited for today, too!"
    levania "Hmph."
    carrier "Yes? What might you need?"
    levania "Do you come here a lot?"
    carrier "Indeed—one might even call it my workplace!"
    carrier "Not to boast, but I received the performance MVP award for this past year!"
    levania "It was a yes or no question."
    carrier "Such a harsh response!"
    carrier "Now then, let us get to restoring tonight's memories."
    levania "If that's what it'll take to become human, fine."
    
    scene image "09_piles_of_leaves/04_traveling_change_up.png"

    #Story 1 1:49
    scene image "blackscreen.jpg"
    levania "The path I was shown descended endlessly. Human stories are filled with obsession, jealousy, hatred, grudges, and hypocrisy. However commonplace and boring an observation it may be, humans can seemingly only find themselves in interactions with others."
    levania "And those were also the girl's nightmares. She showed restlessness, sympathy, dread, and grief at every twist and turn... And I saw her as an innocent little creature."
    levania "A creature the exact opposite of myself."
    levania "I felt not so much disgust, but fear."
    levania "Fear that I had somehow taken an interest in this pure girl."
    
    scene image "09_piles_of_leaves/05_post_levania.png" 
    fio "I hope the dream isn't scary."
    

    scene image "09_piles_of_leaves/06_Story_1.png"
    "Story 1: gUIdANcE"
    
    scene image "09_piles_of_leaves/07_establishing_shot.png"
    "The woman wakes in a dark and crumbling place."
    "Pain races through her body."
    "She thought she would die when she saved her husband from the commander."
    scene image "09_piles_of_leaves/08_walking_why.png"
    "Yet she is still alive. But...why?"
    "Trying to make sense of her piecemeal memories, she starts walking."
    "Her location is a mystery."
    scene image "09_piles_of_leaves/09_bodies.png"
    "Eventually, she discovers people clad in the same clothing as her collapsed among some rubble."
    "They appear to be dead."
    "They no longer draw breath."
    
    scene image "09_piles_of_leaves/10_reunion.png"
    "Suddenly, her husband appears, along with some of her old fellow prisoners."
    husband "You... You're alive!"
    "The joy they feel in this moment is beyond all measure."
    #Story 1 end

    #fio "Welcome back! Did you have fun?" Not overly story important.
    #carrier "It seems to be a continuation of yesterday's dream."
    #fio "The one about the man who lost his family?"
    #carrier "The very same—although happily, it seems the wife had survived."
    #fio "Yay!"
    #fio "Say, Mr. Monster? Do you have any siblings?"
    #levania "I do not know—or care."
    #fio "I'm an only child, and I'd do ANYTHING to have a brother or sister!"
    #fio "So, um...do you have a favorite food?"
    #levania "Whatever I can eat."
    #fio "My mommy makes yummy stew."
    #fio "Do YOU like stew?"
    #levania "I don't know what that is."
    #levania "I understand nothing you humans go on about. Keep quiet."
    #fio "Awww..."
    #fio "Look, Mr. Monster! Look, Carrie! It's the next scarecrow!"
    #carrier "Carrier?"
    #Ca...rrie?: "Ca...rrie?"
    #levania "At least I'm not the only one with an insipid nickname."
    #fio "Good luck, Mr. Monster!"
    

    # Story 2 start
    scene image "09_piles_of_leaves/11_story_2.png"
    "Story 2: ReVOLt"
    scene image "09_piles_of_leaves/12_establishing_shot.png"
    "The woman is brought to a base for former prisoners."
    husband "Why not try talking to everyone?"

    scene image "09_piles_of_leaves/13_talking_1.png"
    defectiveMan "Everyone here is considered 'defective.'"
    defectiveMan "Isn't that a laugh? If anyone's messed up, it's the organization."
    defectiveWoman "I don't want to be cast aside because I think for myself!"
    defectiveMan "The organization doesn't know what it's doing!"
    defectiveWoman "We want to free the others."
    defectiveMan "We may not be under their thumb anymore, but we can still fight."
    defectiveMan "Don't you agree?"
    defectiveMan "You've seen first-hand how the organization treats defectives."
    
    scene image "09_piles_of_leaves/14_pain_in_head.png"
    husband "What happened after the commander stabbed you?"
    "Pain shoots through her head. She can't remember anything after being separated from her husband."
    scene image "09_piles_of_leaves/15_base_attack.png"
    defectiveMan "They're attacking the base!"
    "As part of their resistance to the organization, the defectives had been plotting ways to free their fellow prisoners"
    husband "Well then, it's about time we go say hello."
    
    scene image "09_piles_of_leaves/16_attack_response.png"
    husband "Stay close to me."
    scene image "09_piles_of_leaves/17_confrontation.png"
    husband "We don't want to fight! Stop this! Wake up!"

    scene image "09_piles_of_leaves/18_casualty.png"
    husband "Dammit!"
    "The organization had ordered the prisoners to hunt down the escaped defectives."
    husband "We'll all be killed if we keep this up."
    husband "It's time to put our plan into action."
    #Story 2 end 

    #carrier "It seems this story will not end happily after all..." Not important enough.
    #fio "Oh..."
    #fio "So what's YOUR favorite food, Carrie?"
    #carrier "I love nothing more than a heaping plate of dried and salted fish eggs!"
    #fio "Blech!"
    #carrier "It may be something of an acquired taste. Perhaps you need to be older to enjoy it."
    #fio "Have you had salty fish eggs, Mr. Monster?"
    #levania "No."
    #fio "Hee heel! That means you're a kid, too!"

    #Story 3 Start
    scene image "09_piles_of_leaves/19_story_3.png"
    "Story 3: fiCTIOn"
    scene image "09_piles_of_leaves/20_enemy_hq.png"
    "Despite the organization's orders, the defective prisoners have a plan:"
    "During the next Flower attack, they will sneak into the organization's HQ."
    "Once there, they will free all the remaining prisoners in one fell swoop."
    husband "Let's blend in with the returning soldiers and enter the base."
    "Acting as an advance scout team, the man and his wife enter the HQ."
    "They had spent so much of their lives here..."
    "But this was the first time they were able to move about of their own volition."

    scene image "09_piles_of_leaves/21_inside_base.png"
    "They had trained here for days without end."
    "All so they could exact revenge on the Flowers that stole their son."
    "Everyone here was the same. They all had a reason to want the Flowers dead."
    "But in that case, why were they shackled by so many unnecessary rules?"
    "In all of their time here, they had never stopped to wonder why this was."
    
    scene image "09_piles_of_leaves/22_security_scan.png"
    "Security:  Scanning ID..."
    "Security: ID approved."
    
    scene image "09_piles_of_leaves/23_the_room.png"
    "This is the first time either of them has ever set foot in the incubation room."
    "Sleeping prisoners float peacefully inside liquid-filled capsules."
    husband "What is this place?"
    
    scene image "09_piles_of_leaves/24_officer.png"
    officer "I knew you would come."
    "The husband and wife defeat the confruting officer with ease."
    "The officer lies defeated at their heels."
    scene image "09_piles_of_leaves/25_officer_defeat.png"
    officer "You've grown stronger. Good... Very good..."
    "The commander begins to tell his tale."
    "Humans—true humans—no longer exist."
    "You prisoners are nothing but clones. Pale imitations."
    "And in order to give you a reason to fight, we implanted you with...memories."
    officer "You wanted revenge after your son was killed, didn't you?"
    officer "Lend us your aid."
    "Their pain. Their desire for revenge. It all stemmed from their son's death."
    scene image "09_piles_of_leaves/26_officers_test.png"
    officer "This is... your final test..."
    scene image "09_piles_of_leaves/27_mind_control.png"
    "_________"

    #carrier "Human clones. Oh dear." Is the cursed god really story important i wonder....
    #fio "What's a 'clone'?"
    #carrier "It might be a touch difficult for you to understand, young miss."
    #levania "What's that huge... thing?"
    #Flo: "Is that... a mo[...]"
    #fio "Is that a... moose?"
    #carrier "That is a cursed god; it being in this part of The Cage brings wickedness!"
    #carrier "Goodness! Is this your summoning power!?"
    #carrier "Good luck! I shall stand aside and cheer you on from a safe distance!"
    #fio "Don't get hurt, Mr. Monster!"
    #carrier "You have defeated a cursed god! I am nothing less than impressed."
    #fio "You're so cool, Mr. Monster!"
    #levania "Divinity means nothing to me, after all."
    #carrier "I have heard that some even pray to those cursed gods. How terribly dreadful!"
    #fio "Is it a bad moose?"
    #carrier "Oh yes. It has a grisly face, and likes to appear right in front of you!"
    #fio "And that's...bad?"
    #carrier "Color me impressed that you did not flinch in the face of the cursed god."
    #fio "Were YOU scared, Carrie?"
    #carrier "I, ah, er... Yes."
    

    # Story 4 Start
    scene image "game/images/09_piles_of_leaves/28_story_4.png"
    "Story 4: fAte"
    scene image "09_piles_of_leaves/29_false_memories_1.png"
    "Memory"
    scene image "09_piles_of_leaves/30_false_memories_2.png"
    "False"
    scene image "09_piles_of_leaves/31_false_memories_3.png"
    "Memory"
    scene image "09_piles_of_leaves/32_false_memories_4.png"
    "False"
    scene image "09_piles_of_leaves/33_false_memories_5.png"
    "Memory False"
    scene image "09_piles_of_leaves/34_false_memories_6.png"
    "kill the enemy"
    "kill your loved one"
    
    #"Die together so your husband won't have to live without you." TODO add later
    #"Die so that your husband can live."
    #"Make your choice."
    
    scene image "09_piles_of_leaves/35_final_moment.png"
    woman "The woman tells her husband she will soon lose herself."
    "She remembers a process the commander installed in her the first time she died"
    "A setting that deletes even her false self, making her a mindless weapon of carnage."
    husband "Let's end this. Together."
    scene image "09_piles_of_leaves/36_final.png"
    "......."

    scene image "blackscreen.jpg"
    "P.A: Mutual death confirmed. Cause: Marital bonds."
    "P.A: Data saved as reference for future clone development."
    "P.A: Test concluded."
    #Story 4 End 22:54

    scene image "09_piles_of_leaves/37_mr_monster.png"
    carrier "Death borne from love for her partner..."
    carrier "There is a very fine line between joy and misery."
    levania "I don't understand either of those emotions."
    carrier "In any case, it is now the moment you have been waiting for: dream time!"
    carrier "It seems it is almost morning in the other world."
    fio "Thank you. And, um... I wish we could have adventured more together."
    carrier "We shall meet again once night falls. Come now."
    scene image "09_piles_of_leaves/38_fio_leaves.png"
    carrier "Let us be off, shall we?"
    carrier "You've grown used to gathering dreams, haven't you? Well, let's keep up the pace!"
    jump flaming_sands
    