

#The Third Night: Flaming Sands
label flaming_sands:
    scene image "10_flaming_sands/01_opening.png"
    "— Musings of a lonely boy"
    scene image "10_flaming_sands/02_establishing_shot.png"
    ""
    scene image "10_flaming_sands/03_fio_entrance.png"
   
    carrier "And there we are!"
    carrier "Pardon me, you two, but I fear management has given me something of a sudden summoning."
    carrier "Might it be all right if a substitute took care of you today?"
    scene image "10_flaming_sands/04_meeting_tutie.png"
    carrier "Ah, speak of the dickens! Here comes the substitute now!"
    substitute "Nice to make your acquaintance."
    carrier "Worry not; I shall be returned before you know it. Ta!"
    substitute "I'm your substitute carrier."
    fio "If you're a substitute, I'm gonna call you Tutie!"
    #substitute "To get through here you gotta pull this lever."
    #fio "I need to pull the lever? Got it. Thanks, Tutie!"
    #fio "Wooow! It's like there are waterfalls of sand!"
    fio "Oh! I think I forgot about my dream from last night!"
    fio "You really are amazing, Mr. Monster."
    levania "I am not eating your dreams for you, you know."
    scene image "10_flaming_sands/05_scarecrow.png"
    substitute "This will be our first scarecrow of the day."
    levania "Yes, I am well aware."
    fio "Have fun! Byeee!"
    
    scene image "10_flaming_sands/06_story_1.png"
    "Story 1: Childhood Memories"

    scene image "10_flaming_sands/07_establishing_shot.png"
    "The boy lives in a country that has been beset by a long, drawn-out war."
    "Each night, gunfire erupts and stirs his anxiety."
    scene image "10_flaming_sands/08_family_house.png"
    "Frightened, he heads to the living room to be with his parents."
    
    radio "The enemy forces continue their advance..."
    radio "There have been many casualties..."
    father "What's wrong, kiddo? Can't sleep?"
    mother "There's no need to look so worried, dear!"
    scene image "10_flaming_sands/09_family_house_1.png"
    "His mother's smile always manages to cheer the boy up."
    mother "It's all right, dear."
    mother "The soldiers will protect us."
    "Though he is a coward at heart, he says this for the sake of his beloved mother,"
    child "One day I'll be a soldier and keep you safe, Mom."
    "His mother breaks into a wide, happy smile at his words."

    scene image "10_flaming_sands/10_family_house_hide.png"
    "Suddenly, there is a loud noise from the entrance to the home."
    father "The hell was that?"
    father "Better take a look."
    mother "Go hide in the closet, okay, dear?"
    father "Get the boy out of here! Hurry!"
    mother "Aaaaah!"
    
    scene image "10_flaming_sands/11_soldier.png"
    "His parents scream for a long, agonizing moment."
    "And then they fall silent."
    enemyCaptain "Where is he!?"
    "The enemy soldier overlooks the boy and leaves."
    
    scene image "10_flaming_sands/12_parents.png"
    "He nervously makes his way to the corridor where he'd heard his parents' terrible screams."
    "He finds the corpses of his parents cooling on the floor."
    "He inches closer and examines the sword that is impaled in his father's still form."

    scene image "10_flaming_sands/13_symbol.png"
    "It is decorated with a distinctive emblem."
    
    scene image "10_flaming_sands/12_parents.png" # Yes refering to prev image.
    "The boy crumples to the floor and begins to sob as shame at his weakness overwhelms him."
    "Even now, the thought of the enemy he saw from the closet makes him go weak in the knees."
    "He is a coward. A craven. A sniveling child who had been unable to act."
    #Story 1 end

    #fio "Was it another bad dream?"
    #fio "Whoa, these stairs make sounds!"
    #fio "Isn't this fun, Mr. Monster?"
    #levania "Not really."
    #fio "Is this making you dizzy?"
    #levania "I am fine."
    
    #Story 2 start
    scene image "10_flaming_sands/14_story_2.png"
    "Story 2: Building Rage"
    scene image "10_flaming_sands/15_soldier.png"
    "Years pass. The boy that lost his parents has become a soldier."
    tannedSoldier: "Hey, you're on watch."
    "He did so for one reason: To find the man who ruined his life and kill him."
    "Once afraid, the boy is now possessed by naught but pure, unyielding vengeance."
    
    scene image "10_flaming_sands/16_encounter.png"
    brawnySoldier "Hey! Pipsqueak! Where ya headed?"
    brawnySoldier "I'm here to teach ya a lesson, so I am..."

    "The other troops often single out the unsociable boy."
    "The boy stares back at the soldier before him."
    "The coward he once was is now a distant stranger."
    brawnySoldier "Lemme hear ya cry, pipsqueak!"
    
    scene image "10_flaming_sands/17_encounter_captain.png"
    captain "Hey!"
    captain "Please stop, okay?"
    brawnySoldier "....."
    brawnySoldier "Pfft! What a buzzkill."
    "Their captain steps in to stop the quarrel."
    "But rather than look at him, the boy turns away."
    "Though a captain, the man is rather soft and weak-willed."
    "When the boy looks at him, it is like looking at the coward he once was."
    "Turning his back on his caring captain, the boy departs."
    captain "......"
    "This is a tale of burning revenge."
    #Story 2 end

    #fio "What's 'revenge'?"
    #levania "When someone harms you, you repay them in kind."
    #fio "That's bad!"
    #levania "The world would be terribly unfair otherwise, no?"
    #fio "My teacher said it's bad!"
    #fio "I wonder where Carrie went."
    #levania "Who cares?"
    #fio "Eeep! That was scary!"
    

    #Story 3 start
    scene image "10_flaming_sands/18_story_3.png"
    "Story 3: Dispair and Hope" 

    scene image "10_flaming_sands/19_breifing.png"
    "The next day, the soldiers are briefed on their upcoming operation."
    "Each one of them receives a set of materials."
    "When the boy looks at the documents, a terrifying smile slowly emerges on his face."
    "For on the first page is the same emblem that was on the sword all those years ago."
    scene image "10_flaming_sands/20_symbol.png"
    "......"
    scene image "10_flaming_sands/19_breifing.png" # refer to prev image.
    "His sworn enemy was close now. So very close."
    "The boy feels his blood begin to boil as he considers this..."
    "Then he slowly makes his way to the captain."
    captain "Yes? What is it?"
    "There is a man among our foes—
    the same man who killed my parents."
    "I owe this man; the debt must be paid. Put me in the front line so I may take his life!"
    captain "I understand how you feel, but I cannot. I'm sorry."
    scene image "10_flaming_sands/21_sword_to_captain.png"
    "Enraged, the boy draws his weapon and moves to attack his own captain."
    "Though the other man quakes in fear, he does not rescind from his previous order."
    scene image "10_flaming_sands/22_departs.png"
    "The boy hurls abuse at the timid man as he sheathes his weapon and departs."
    scene image "10_flaming_sands/23_plotting.png"
    "As the other soldiers sleep, the boy stirs."
    "If he can't get permission, he will simply act alone."

    scene image "10_flaming_sands/24_night_watch.png"
    brawnySoldier "Hey! Pipsqueak! Where do ya think YOU'RE goin'!"
    brawnySoldier "Ain't no captain around to help ya now! Haw haw!"
    "It is the same burly soldier who always tries to fight him."
    "I came to apologize for what happened earlier."
    "I'm here to relieve you. It's my turn on patrol."
    "The boy lies."
    brawnySoldier "Well, took ya long enough."
    brawnySoldier "No slackin' off, yeah?"
    scene image "10_flaming_sands/25_alone.png"
    "Though this soldier usually irritates him, today he pays him no mind."
    "Instead, he bends all his thought on the man who took his parents from him."
    "He has killed him over and over in his imagination, but now..."
    #Story 3 end

    #substitute "Entering enemy territory alone is very reckless."
    #fio "Why do you wanna be human, Mr. Monster?"
    #levania "It is an instinct among my kind."
    #fio "Ohh... In-stink, huh?"
    #fio "When I grow up, I have an in-stink to be a ballerina!"
    #fio "I've wanted to be one ever since I read a picturebook about ballerinas."
    #fio "Do you think I can be one?"
    #levania "I'm certain I have no idea."
    #substitute "This will be today's last scarecrow."
    #fio "Good luck!"
    
    #Story 4 Start
    scene image "10_flaming_sands/26_story_4.png"
    "Story 4: A Night Without a Dawn"

    scene image "10_flaming_sands/27_enemy_camp.png"
    "The boy infiltrates the enemy camp just before daybreak."
    "The rows of tents are silent in the shadow of dawn."
    "A small fire burns in a tent deep within the camp, and he senses the presence of an enemy."

    scene image "10_flaming_sands/28_enemy_investigation.png"
    enemySoldier "Huh? Who's there?"
    scene image "10_flaming_sands/29_enemy_killed.png"
    enemySoldier "Aaaugh!"
    scene image "10_flaming_sands/30_enemies.png"
    enemySoldier "It's the enemy!"
    enemySoldier "It's him."

    "As hatred flares inside him, the boy strikes at the man with all of his might."
    enemySoldier "Kill him! Kill the enemy!"
    enemySoldier "Take him out!"
    enemyCaptain "You're..."
    enemySoldier "This one's tough!"
    scene image "10_flaming_sands/31_enemy_defeat.png"
    enemySoldier "Dammit!"
    scene image "10_flaming_sands/32_captain.png"
    enemyCaptain "No..."
    scene image "10_flaming_sands/33_captains_death.png"
    enemyCaptain "...!?"
    enemyCaptain "You're... No! It can't be!"
    "The enemy captain looks the boy square in the eyes."
    "And then, his voice unsteady, he murmurs something."
    "He pauses, coughs up a gout of blood, and tries again"
    enemyCaptain "I...understand."
    enemyCaptain "I'm so sorry..."
    enemyCaptain "I'm sorry I couldn't save you."
    scene image "blackscreen.jpg"
    "Lying on death's door, the enemy soldier says his piece."
    "He tells the boy the truth of that fateful night"
    "He was not a random soldier, but the boy's own father."
    "The couple were not his parents, but brigands who stole him from the cradle."
    "With a trembling hand, the man hands the boy a small notebook before breathing his last."
    "In it, he learns his home country ran a kidnapping scheme targeting infants."
    "Glued within the pages are multiple pictures of the couple who raised him."
    "His parents are a sin; his life a sham. He has devoted his existence to... nothing."
    scene image "10_flaming_sands/34_dispair.png"
    "The battlefield lies in a cold, hollow silence as the sun slowly begins to rise..."
    #Story 4 ends

    scene image "10_flaming_sands/35_cage_1.png"
    substitute: "It is time for tonight's dreaming."
    scene image "10_flaming_sands/36_cage_2.png"
    carrier "I have returned! Terribly sorry to have caused you so much trouble."
    carrier "It's always such a shock to be called in on short notice like that. I do wish they would find a different way..."
    substitute "Well then, I'm off."
    fio "Let's play again sometime, Tutie!"
    substitute "Okay."
    fio "I wish I could stay here forever."
    scene image "10_flaming_sands/37_cage_3.png"
    carrier "I doubt that is possible, milady."
    carrier "You are not part of this world, you see."
    levania "See you tomorrow night."
    carrier "Now then... There we go!"
    fio "I'll be right back, so just wait. Okay, Mr. Monster? You too, Carrie."
    levania "Oh, with bated breath..."
    carrier "Dear me, I've not been here long and I am already covered in sand. I could use a quick soak in the tub!"
    jump fourth_night
    