


label fourth_night:#Done 100% untested.
    scene image "11_the_fourth_night/01_opening.png"
    "-Conversation within a platoon"
    
    scene image "11_the_fourth_night/02_establishing_shot.png"
    ""
    scene image "11_the_fourth_night/03_fio_mr_monster.png"
    levania "I've been waiting for you."
    fio "Hee hee Thanks."
    carrier "Now, let us proceed onward. Briskly now, friends! Briskly!"
    #fio "So it's nighttime here, too."
    #carrier "Yes, it does indeed seem that way sometimes."
    #fio "Oh no! They broke!"
    #fio "Are we gonna get in trouble?"
    #carrier "Now let us begin with this Dark Scarecrow."
    

    #Story 1
    scene image "11_the_fourth_night/04_story_1.png"
    "Story 1: Captain Craven"
    scene image "11_the_fourth_night/05_story_establishing.png"
    "A timid military captain lives in a nation where wars rage without pause."
    "His frequent retreats have caused his men to nickname him 'Captain Craven.'"
    "This morning, he walks around the base and orders his men to prepare for combat."

    scene image "11_the_fourth_night/06_argument.png"
    angrySoldier: "This idiot drank my beer last night!"
    drunkSoldier: "I SCHAID I was schorry! Whaddya want from me!"
    captain "Let's all calm down, okay? I'll go buy some more later."

    scene image "11_the_fourth_night/07_argument_1.png"
    lazySoldier "Sooo, I kinda forgot the details of today's operation?"
    seriousSoldier: "You're the one in charge of preparation!"
    captain "It's all right. I'll take care of getting everything ready."
    
    scene image "11_the_fourth_night/08_captains_troubles.png"
    "Daily, the captain finds himself mediating quarrels among his hot-blooded men."
    "And yet, he never treats them as anything other than his trusted fellows."
    
    scene image "11_the_fourth_night/09_dicipline.png"
    loudSoldier "Heeey, Captain Craven!"
    loudSoldier "Yeah, we're all sick of you. Any chance you can just go off and die somewhere?"
    "After finishing his rounds, the captain restores a temporary discipline."
    loudSoldier "All right. I'll head back and get ready for the operation."

    scene image "11_the_fourth_night/10_unaccounted_for.png"
    brawnySoldier: "Captain, that problem child from yesterday is unaccounted for."

    "Earlier, a young boy had volunteered for combat so he could avenge his parents."
    "But concerned for the boy's well-being, the captain had turned down his proposal."
    "Dark clouds gather as they ready for combat, matching the captain's mood..."
    
    scene image "11_the_fourth_night/11_fio_mr_monster.png"
    carrier "My substitute said these are stories of war related to last night's dreams."
    fio "Hmm, 'Stories of war,' huh?"
   
    scene image "blackscreen.jpg"
    "The girl always looked to be having fun as we traveled. She had been plagued by nightmares and spent untold nights in tears in her old life, 
    but she looked downright cheerful in the world of The Cage.
    Even though humans are at the whims of their emotions, it seems their souls shone brighter with each bout of emotional turmoil, and I could not understand why.
    But that was the first time that I knew I wanted to be human so I could see the world from the same perspective as her."
    
    scene image "11_the_fourth_night/11_fio_mr_monster.png" # Prev used image
    fio "I hope you can be human soon, Mr. Monster."
    levania "Judging by your dreams, it seems all you humans do is worry and fret."
    levania "Do you even enjoy your lives?"
    fio "Well, / sure do!"
    fio "I play with my friends, eat snacks, read books..."
    fio "I get to be with my mommy and daddy..."
    fio "....."
    levania "Mmm? What is it?"
    fio "N-nothing..."

    #boy "Mommy... *sniff*" I don't find it imporant enough as the kid just get left waiting for his mom anyway. :/
    #levania "What is this child doing here?"
    #carrier "Dear me, I have no idea."
    #fio "What's wrong?"
    #boy "A buncha mean soldiers came to the village, so me and my Mommy were gonna 'scape..."
    #boy "But I got lost... *sniff*"
    #carrier "Heavens, I believe this child was chased here from inside the scarecrow!"
    #levania "Can that even happen?"
    #carrier "It appears so—though I imagine it to be a rather rare occurrence."
    #boy "*sniff* I want my mommy... *sniff*"
    #fio "Can you go find his mommy in the scarecrow, Mr. Monster?"
    #fio "Pleeeease?"
    #carrier "You will be entering the Dark Scarecrows regardless, so I suppose it could not hurt to search for the missing mother as well."
    #levania "I didn't think this could get any more annoying, yet here we are."
    
    #Story 2 Start
    scene image "11_the_fourth_night/12_story_2.png"
    "Story 2: Familiar Impression"
    scene image "11_the_fourth_night/13_establishing_shot.png"
    "With several units in tow, the captain and his army march for the enemy camp."
    "Their goal is to annihilate the enemy—and, if possible, locate the missing boy."
    captain "Alpha Team, proceed to Point B as planned."
    captain "Charlie Team, scout the enemy numbers from the west."
    "As always, his orders are cautious; the safety of his men his overriding concern."

    scene image "11_the_fourth_night/14_panicked.png"
    "The victims of the war run from the inpending death..."
    "The village is done for!"
    "Just keep going!"
    "Run! RUUUN!"
    "My son... Where is my son...?"

    scene image "11_the_fourth_night/15_captain.png"    
    captain "Alpha Team, we'll soon arrive at Point D."
    captain "We'll prepare there and await further situation reports."
    "The captain and his men soon arrive at the enemy camp."
    "As planned, another team initiates a feint attack to draw attention."
    scene image "11_the_fourth_night/16_captain_1.png"
    "Cautiously, the captain moves into the enemy camp."
    scene image "11_the_fourth_night/17_enemy_corpse.png"
    "After a moment, he locates the bloodied corpse of the enemy commander."
    scene image "11_the_fourth_night/18_enemy_corpse_1.png"
    "A familiar blade protrudes from a hole in his chest."
    "He knows this sword—the missing boy had pointed it at him the night before."
    "But the boy is nowhere to be found, and the captain knows he is in grave danger."
    "He stares at the scene before him and whispers,"
    "Have I failed again?"
    # Story End
    
    #fio "Did you find the boy's mommy?"
    #levania "....."
    #fio "Hmmm..."
    #fio "Hey, why don't you come with us so we can look for your mommy together?"
    #boy "Kay, I'll go with you. Thanks!"
    #fio "Yay! He's coming with us, Mr. Monster! Isn't that great?"
    #levania "......."
    #carrier "So the woman inside the scarecrow who died while searching for her son..."
    #carrier "That was the boy's missing mother, yes?"
    #carrier "If I may, why do you not tell him the truth?"
    #Enemy: "An enemy from within the Dark Scarecrow!?"
    #Resentful Witch: "My son..."
    #Resentful Witch: "Where is my son...?"
    #fio "Oh no. Could she have been...?"
    #boy "That's... No! That wasn't my mommy!"
    #fio "Could you search the scarecrow again, Mr. Monster?"
    #levania "...Fine."
    
    #Story 3 Start
    scene image "11_the_fourth_night/19_story_3.png"
    "Story 3: I'm Glad You Survived"

    scene image "11_the_fourth_night/20_establishing.png"
    "Years ago, the cowardly captain was but a meager foot soldier."
    "He possessed the arrogance of youth, and often butted heads with his commanders."
    "After one intense battle, he found himself searching for any surviving comrades."

    scene image "11_the_fourth_night/21_finding_corpse.png"
    youngMan "You're..."
    "The first corpse he found was a senior officer who used to bark orders at him."
    
    scene image "11_the_fourth_night/22_finding_officer.png"
    youngMan "...!"
    "The next, a fellow soldier with whom he often fought."
    "He had done this—he had ignored orders and brought his squadron to ruin."

    scene image "11_the_fourth_night/23_finding_captain.png"
    "As he cursed himself, he found a survivor: an officer whom he had often mocked."
    officer "Ah, you live... Good. That's...good."
    officer "I'm glad you survived..."
    "The officer closed his eyes, let out a final, blackened breath, and died."
    
    scene image "blackscreen.jpg"
    "This is all your fault!"
    "You're always so selfish!"
    "You killed all of us!"
    "I'm glad you survived..."
    "Those words would haunt the young soldier for the rest of his days."

    scene image "11_the_fourth_night/24_eight_year_later.png"
    "Eight years later..."
    "Though fearful at the thought of losing his men, he continued on as a soldier."
    "He now attempts to atone for his mistakes by ensuring no one else has to die."

    scene image "11_the_fourth_night/25_found.png"
    "Finally, he finds the boy wounded and hiding behind a bit of cover."
    "His heart skips a beat; it is like seeing himself some eight years ago."
    "I will do whatever I must to save him."
    "With that thought in mind, the captain reaches down for the injured boy."
    #Story 3 end

    #fio "Did you find her, Mr. Monster?"
    #levania "No."
    #boy "I'm gonna wait here for my mommy."
    #fio "But it's not safe! What if those nasty dark things come back?"
    #boy "If I leave, my mommy won't be able to find me."
    #fio "...Okay. I understand."
    #boy "Thank you! Bye, Mr. Monster!"
    #levania "....."
    #boy "I'm gonna be a good boy and wait here till my mommy comes."
    #carrier "You were unable to tell him the truth, it seems."
    #levania "I've no interest in making a child cry."
    #fio "*huff* *huff*"
    #levania "Is something the matter?"
    #fio "N-no... Um, so, the next dream is the last one, right?"
    #levania "You appear tired. Is this because I am eating your dreams?"
    #carrier "Don't be daft. The act of having dreams eaten has no physical effect on a person."
    #fio "I'm okay. Don't worry."
    #fio "*huff* *huff*"
    #carrier "This is tonight's final scarecrow!"
    #Narrator: "One cannot help but wonder what will become of the boy and the captain..."
    
    scene image "11_the_fourth_night/26_story_4.png"
    "Story 4: None Left Behind"

    scene image "11_the_fourth_night/27_carrying.png"
    "The captain hauls the boy onto his back and starts making his return to the base."
    "Despite the danger, he continues issuing orders remotely as they travel."
    "He will not rest until every last one of his men is seen safely out of harm's way."
    captain "Alpha Team, fall back once you've destroyed the enemy armory."
    captain "Beta Team, move prisoners to the camp. Charlie Team, return to base."
    "Suddenly, the boy on his back emits a small groan."
    "In a thin voice, he admits his error and apologizes for his selfish actions."

    scene image "11_the_fourth_night/28_encounter.png"
    Enemy Commando: "DIIIIIE!"
    "Though he managed to save the boy, the captain has taken a most grievous wound."
    "If another enemy were to find them now, he likely will not be able to fend them off."
    scene image "11_the_fourth_night/29_push_on.png"
    "Pushing aside the pain, he continues his march."
    
    scene image "blackscreen.jpg"
    "Its all your fault!"
    
    #Dialogue Options:
    #- "I won't repeat my mistakes!"
    #- "I'm a different man now!"

    griff "I won't repeat my mistakes!"
    griff "I'll find a way to save every last man!"
    "Your arrogance is killing our allies!"
    "I won't repeat my mistakes!"
    "I'm a different man now!"
    griff "I'm a different man now!"
    griff "No one will die on my watch!"
    griff "And if that comes at the cost of my own life...so be it."
    
    scene image "11_the_fourth_night/29_push_on.png" # Refer to old image
    "The captain is reaching his physical limit."
    "He will leave no man behind. He will let no man die. It is a naive belief, yet it keeps him going."
    scene image "11_the_fourth_night/30_encounter.png"
    "Soon, another enemy force appears to bar their way."
    "The captain stares them down, placing his own body between them and his young charge."
    
    scene image "11_the_fourth_night/31_reinforcements.png"
    "Suddenly, the rest of his squad appears."
    "Breaths are held. Fingers lie tense on weapons. One false move will mean a slaughter."
    scene image "11_the_fourth_night/32_fallback_1.png"
    "Finally, after a long moment, the enemy retreats."
    "The squad had come to their captain's aid."
    scene image "11_the_fourth_night/33_fallback_2.png"
    "Miraculously, they have all survived the mission."
    scene image "11_the_fourth_night/34_final.png"
    "With his eyelids heavy, he murmurs to the boy,"
    "I'm glad you survived..."
    "His men—the family he built at the cost of his pride—have saved him."
    "They pick the boy up and begin to tease him, saying he's lucky to be alive."
    "The boy responds with a dry smile—the first time any of them remember him doing so."
    "The sound of their laughter rings out happily across the desolate battlefield..."
    # Story 4 End

    scene image "11_the_fourth_night/35_mrmonster_fio.png"
    carrier "My word, a happy ending! How terribly unusual."
    carrier "It's good to see that the captain's wish to not let anyone die seems to have prevailed."
    scene image "11_the_fourth_night/36_fio_leaves.png"
    carrier "And now, for our favorite event: dream time!"
    fio "I guess I go back now, right?"
    levania "You're acting...strange."
    fio "I'm okay."
    fio "Um, see you... tomorrow..."
    #carrier "And there we have it!"
    scene image "11_the_fourth_night/37_final.png"
    carrier "Hmm. I fear something in the other world may be causing her to weaken."
    levania "And what exactly would that 'something' be?"
    carrier "No need to worry about that, mmm?"
    carrier "It's not as if it affects you."
    carrier "Tomorrow, you shall feast on her dreams and take another step in your quest to become human!"
    jump mist_on_the_water
    